### ISSUE TITLE
Maven installation problem: Could not resolve dependencies

### ISSUE THREAD

**Issue by ahab94** [iotaledger/iota.lib.java#100]
Been facing dependencies installation issues, for installing jota locally.

![jota bug 1](https://user-images.githubusercontent.com/19879385/39128733-ffe268bc-4721-11e8-9feb-190b0ffd7cfc.PNG)
As you can see in the above image, this is the index which maven resolves to leveraging the `pom.xml`.
However the `pom.xml` file in the index redirects to other directory. Which is called `jota`.
```XML
<dependency>
<groupId>com.github.iotaledger.iota.lib.java</groupId>
<artifactId>jota</artifactId>
<version>0.9.7</version>
</dependency>
```
![jota bug 2](https://user-images.githubusercontent.com/19879385/39128735-002187e0-4722-11e8-8659-244be6e96bfd.PNG)
However if you traverse directly to this directory, jitpack says it doesn't exist. The below image suffices maven's order of fetching the jar.
![jota bug 3](https://user-images.githubusercontent.com/19879385/39128736-006373c6-4722-11e8-9a69-2fb8d519201d.PNG)

There are two possiblities. Either the `jota` directory on that index is deleted or restricted.
Someone with access to jitpack could resolve the issue.

![jota bug 4](https://user-images.githubusercontent.com/19879385/39129172-3c555948-4723-11e8-9f1a-80a57a831e99.PNG)
Another thing is that, the jar is sitting right there for the latest version, however the `pom.xml` is still redirecting to `jota` directory.

**Comment by ijaureguialzo** [comment]
I ended copying the contents of pom.xml from the project repo and adding the jota dependency. I was able to make it run.

My pom.xml dependencies:

```
    <dependencies>
        <dependency>
            <groupId>com.github.iotaledger.iota~lib~java</groupId>
            <artifactId>jota</artifactId>
            <version>0.9.10</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.58</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>retrofit</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>converter-gson</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.6</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.5</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.jadler</groupId>
            <artifactId>jadler-all</artifactId>
            <version>1.3.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
```

Hope it helps.

**Comment by ahab94** [comment]
Thanks @ijaureguialzo!

**Comment by kwek20** [comment]
Hey @ahab94  @ijaureguialzo  
I have updated the maven instructions in the README. 
Our default jar is exported with just our classes, and no dependencies.
If you wish to get the dependencies jar instead, add the following to your `<dependency>`
`<classifier>jar-with-dependencies</classifier>`

Example:
```
<dependency>
    <groupId>com.github.iotaledger.iota~lib~java</groupId>
    <artifactId>jota</artifactId>
    <classifier>jar-with-dependencies</classifier>
    <version>17e0de8ed5</version>
</dependency>
```

You can replace the version with any other hash (first 10 characters), or a release tag. 
Classifier does not work for 0.9.9 and 0.9.10 because those entire builds are broken.. A new one is on its way!

Please let me know if you have any questions!
