### ISSUE TITLE
IotaAPI#prepareTransfers does not consume remainder

### ISSUE THREAD

**Issue by toonsevrin** [iotaledger/iota.lib.java#14]
Just take a look at the source, it doesn't seem like the remainder parameter is ever used.
Reproduction is as simple as 
`
String remainderAddress = ...;
List<String> transfers = iotaAPI.prepareTransfers(seed, 2, transfers, remainderAddress, inputs);
for(String trytes : transfers)
  System.out.println(remainderAddress.equals(new Transaction(trytes).getAddress());
`
this snippet will never return true as the remainderAddress is always generated!

**Comment by toonsevrin** [comment]
@pinpong

**Comment by pinpong** [comment]
@toonsevrin we can close the issue?
