### ISSUE TITLE
IotaAPI#getBalanceAndFormat bad method

### ISSUE THREAD

**Issue by toonsevrin** [iotaledger/iota.lib.java#18]
1. KeyIndex abuse
Let's say we provide two addresses as input:
One has an index of 5, the other as 10.

Our getBalanceAndFormat query would look like:
`getBalanceAndFormat(addresses, threshold, 5, 0, new StopWatch(), 2)`

Due to the [implementation](https://github.com/iotaledger/iota.lib.java/blob/master/src/main/java/jota/IotaAPI.java#L600) for getBalanceAndFormat the returned inputs will have as keyindices 5 and 6.

2. The end parameter is unused (and not necessary)

**solution**
Instead of having a List<String> addresses as a param, use a Map<String, Integer> indexByAddress or something, or a custom object.

**Comment by pinpong** [comment]
@toonsevrin

 **getBalanceAndFormat** return a list of Input objects. The unnecessary param is already removed.

```
[jota.model.Input@6f195bc3[
  address=TBH9CSFWUHACJSWGA9XDDMNPJ9USPRLJ9FCHDEYDYGOWPQTQUWXMUBCUKTFJRESNBHGJOISFJOLXTLZOB
  balance=14
  keyIndex=6
  security=2
], jota.model.Input@631330c[
  address=TJCVXRWR9QMDWTSNLTAERSIPULNOQMZXW9ZVSRTHOKNHOGSAYMYMTIPYQAJZJGQBQWOOCITAUJIDBIGFW
  balance=1231
  keyIndex=27
  security=2
], jota.model.Input@42f93a98[
  address=DFVYBPSBMDAJBJMWHOWJBIWBJDHSZWWRYRAUWLLYPFZPBHIRGIWAM9QHOPYEYRJDMSVDWZJFPUEJPNFZA
  balance=112
  keyIndex=29
  security=2
], jota.model.Input@c46bcd4[
  address=UPGFQDXOHSDEZFHTPUXQIRQOCTGQYZTDTLAEISKTLKOMXGFNYRFQZNGUXXMZZLKKBWGJOCRKFGZLQNAJX
  balance=5008601
  keyIndex=32
  security=2
]]

```
