### ISSUE TITLE
Add a few sentences on how to contribute to the project

### ISSUE THREAD

**Issue by jpkrohling** [iotaledger/iota.lib.java#22]
Please, add a `CONTRIBUTING.md` with the instructions on how to contribute to this project. For instance, should I expect `master` to be the currently `on development` branch, like other open source projects? Should I expect the tests to pass on the repository's CI?

**Comment by pinpong** [comment]
Hi,

please feel free to open a pull request and add `CONTRIBUTING.md`.

**Comment by jpkrohling** [comment]
Could you please assign this issue to me?

**Comment by heinrichreimer** [comment]
This is fixed by #33, isn't it?

**Comment by jpkrohling** [comment]
Yes :)
