### ISSUE TITLE
Travis and releases

### ISSUE THREAD

**Issue by jpkrohling** [iotaledger/iota.lib.java#32]
Currently, the Travis builds aren't working for PRs. Similarly, it's not clear how a release is made. In fact, it appears that artifacts aren't being released to Maven Central yet.

If there's agreement, I would like to:

- [x] Request a new project with Sonatype, to publish artifacts on Maven Central
- [x] Create a bintray project for this repository
- [x] Deprecate the `dev` branch, by having all development happening on `master`, as it's usual for open source projects. For that, I'd just "force push" the current `dev` to `master` and remove the `dev` branch. Note that the version in the `pom.xml` for master is *always* `-SNAPSHOT`
- [x] Fix Travis to have a build in stages. For instance, this could be used as a reference: https://github.com/opentracing-contrib/java-ejb/blob/master/.travis.yml
- [x] With a setup like the above, creating a new release is just a matter of pushing a tag named `release-x.x.x`, where `x.x.x` is the version to be released
- [x] Document this process by adding a `RELEASE.md` document

**Comment by jpkrohling** [comment]
Please, assign this issue to me. Also, please leave a comment with the users that should be able to push released artifacts to Maven Central.

**Comment by jpkrohling** [comment]
Reference: https://issues.sonatype.org/projects/OSSRH/issues/OSSRH-33850?filter=allopenissues

**Comment by jpkrohling** [comment]
Bintray: https://bintray.com/iotaledger

**Comment by heinrichreimer** [comment]
@jpkrohling isn't the last point on your check list already fixed in #33?

**Comment by jpkrohling** [comment]
Actually, all items should now be fixed. I'll just leave the "release" unmarked, as I don't think we did a release yet, so, there might be still something do to.

**Comment by heinrichreimer** [comment]
You're right. Let's wait then

**Comment by pinpong** [comment]
Can this issue be closed?
