### ISSUE TITLE
findTailTransactionHash

### ISSUE THREAD

**Issue by Cylix** [iotaledger/iota.lib.java#43]
Hi,

I'm implementing a C++ version of this library and I spent some time checking your code.
However, I got confused by your findTailTransactionHash.

From the documentation, it should return a tail transaction hash given a transaction hash.
The thing I don't get is that if the input transaction is not a tail transaction, you recursively call the function with the hash of the bundle which is then used to init a transaction object.
On my C++ port, this does not work and returns an empty hash (hash full of 9's), which limits the use of this function (because it seems it only return the tail transaction hash if the input transaction is a tail).

I tried to check on other implementation but seems this function is only provided on the java client.

Is there something I missed or is there a bug in this function?

On my implementation, I replaced the else branch by a call to findTransactionObjectsByBundle with the bundle hash of the input trx followed by a loop finding the tail transaction.

**Comment by pinpong** [comment]
I have no idea where this comes from. This function is removed by #57
