### ISSUE TITLE
findTransactionsByAddresses doesnt work with addrss with checksum but works without it

### ISSUE THREAD

**Issue by wonkytonky** [iotaledger/iota.lib.java#70]
public void shouldFindTransactionsByAddresses() throws ArgumentException {
        FindTransactionResponse trans = proxy.findTransactionsByAddresses(TEST_ADDRESS_WITH_CHECKSUM);
        assertThat(trans.getHashes(), IsNull.notNullValue());

i was testing this part of code for my own things.. seems that should work without the checksum only

i got the :jota-0.9.6-SNAPSHOT-jar-with-dependencies.jar

**Comment by pinpong** [comment]
This is fixed in [v0.9.10](https://github.com/iotaledger/iota.lib.java/releases/tag/0.9.10).
