### ISSUE TITLE
api.replayBundle() error  : [Invalid tail transaction supplied.]

### ISSUE THREAD

**Issue by wonkytonky** [iotaledger/iota.lib.java#71]
When i tried to replay a tx i got an error: 

jota.error.ArgumentException: [Invalid tail transaction supplied.]
---------------------------------------------------------------------------------------------------------------

	at jota.IotaAPI.traverseBundle(IotaAPI.java:867)
	at jota.IotaAPI.getBundle(IotaAPI.java:637)
	at jota.IotaAPI.replayBundle(IotaAPI.java:761)
	at wonky.Reattacher.getTxByAddres(Reattacher.java:105)
	at wonky.Reattacher.main(Reattacher.java:77)

it was a transactions from bitfinex to wallets. 
https://thetangle.org/address/EWKLBYKFOT9AHLVQJLWTATDHNTCF9KUUXGDOYATGLQUTZKDSRAFHLXZLGGSMERCFRDCIETUTBNX9THWVW

seems bitfinex didnt have a problem reattaching .. 
it has this error somethimes.. and other times it works fine

FindTransactionResponse trans = api.findTransactionsByAddresses("EWKLBYKFOT9AHLVQJLWTATDHNTCF9KUUXGDOYATGLQUTZKDSRAFHLXZLGGSMERCFRDCIETUTBNX9THWVW");
			String[] hashes = trans.getHashes();
			for (int i = 0; i < hashes.length; i++) {
				// get bundle id

				GetBundleResponse bundleResp;

				ReplayBundleResponse replayResponse;

				replayResponse = api.replayBundle(hashes[i], 1, 14);
// this hash fails : XQSPILCRRGFRCJJLSMWJT9YKQRNDSVRQAUPYCLDTYVZXUGDMLPPTO9ECJTYMEYECRGDMWHBYLWLMZ9999  in api.replayBundle(hashes[i], 1, 14);

I use :jota-0.9.6-SNAPSHOT-jar-with-dependencies.jar

**Comment by pinpong** [comment]
You have to provide the `tailTrxHash`.

**Comment by wonkytonky** [comment]
hi this can be closed..   i was indeed providing a wrong tx..
