### ISSUE TITLE
Maven issue

### ISSUE THREAD

**Issue by jacovanc** [iotaledger/iota.lib.java#72]
I'm getting:
`Could not resolve dependencies for project com.mycompany.app:my-app:jar:1.0-SNAPSHOT: Failed to collect dependencies at com.github.iotaledger:iota.lib.java:jar:v0.9.10 -> com.github.iotaledger.iota.lib.java:jota:jar:v0.9.10: Failed to read artifact descriptor for com.github.iotaledger.iota.lib.java:jota:jar:v0.9.10: Could not transfer artifact com.github.iotaledger.iota.lib.java:jota:pom:v0.9.10 from/to jitpack.io (https://jitpack.io): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]`

When I try use this library in a maven project. Any ideas?

**Comment by team2e16** [comment]
Same problem here. Have created a jitpack Access Token and put this into the Maven settings.xml as instructed here: https://jitpack.io/private#auth

Still doesn't work.

**Comment by mudz** [comment]
can compile without any problem
`mvn clean compile`

**Comment by pinpong** [comment]
@Bolwo 

### Maven Dependency

To use the IOTA Java library in your Maven build add this to your root `pom.xml` file:
```xml
<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```

Add this in your module `pom.xml` file:
```xml
<dependency>
    <groupId>com.github.iotaledger</groupId>
    <artifactId>iota~lib~java</artifactId>
    <version>v0.9.10</version>
</dependency>

**Comment by d35h** [comment]
Hi,

I am still experiencing this problem when trying to use the latest version (v0.9.10) of iota, works with v0.9.1 though.

Maven logs:
Could not resolve dependencies for project com.mycompany.app:my-app:jar:1.0-SNAPSHOT: Failed to collect dependencies at com.github.iotaledger:iota.lib.java:jar:v0.9.10 -> com.github.iotaledger.iota.lib.java:jota:jar:v0.9.10: Failed to read artifact descriptor for com.github.iotaledger.iota.lib.java:jota:jar:v0.9.10: Could not transfer artifact com.github.iotaledger.iota.lib.java:jota:pom:v0.9.10 from/to jitpack.io (https://jitpack.io): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]

Any idea?

Thanks,
Dan

**Comment by marimes** [comment]
I seem to have the same problem, i.e. the artifact name is rejected as being invalid. I have added the repository and dependency to pom as specified above.

`[ERROR]     'dependencies.dependency.artifactId' for com.github.iotaledger:iota~lib~java:jar with value 'iota~lib~java' does not match a valid id pattern.`

**Comment by d35h** [comment]
Hi Marimes,

I raised this question on iota's discord and there seems to be no solution so far. However, you can install this library locally.

D

**Comment by marimes** [comment]
Thanks, D. I am new to maven .... I have tried to do this by pulling the repository, mvn compile package, and then use the following command to add locally: `mvn install:install-file -Dfile=./jota-0.9.11-SNAPSHOT.jar -DartifactId=mindliner-local-jota -Dversion=0.9.11 -Dpackaging=jar -DgroupId=org.iota` (I invented an artifact id because I wanted to avoid any potential conflicts). I then updated my pom. When I compiled I ran into some Keccak-related error... How would I correctly add the library locally? Cheers, M

**Comment by d35h** [comment]
Marimes,

You can just clone the project and built it locally, after the build, it should be seen in the logs under which version and artifactId this iota library was registered in your local repo, then you can add this information to your pom.xml to have use install the iota library from your local repo

**Comment by marimes** [comment]
Hi Dan,

when I cloned the repo and mvn compile package install it I get the following output:

[INFO] Installing /Users/marius/IOTA/iota.lib.java/jota/target/jota-0.9.11-SNAPSHOT.jar to /Users/marius/.m2/repository/org/iota/jota/0.9.11-SNAPSHOT/jota-0.9.11-SNAPSHOT.jar
[INFO] Installing /Users/marius/IOTA/iota.lib.java/jota/pom.xml to /Users/marius/.m2/repository/org/iota/jota/0.9.11-SNAPSHOT/jota-0.9.11-SNAPSHOT.pom


I still don’t know how to derive the dependency that I need to put in pom from this one. I know I should read up properly on maven but would appreciate a pointer.

Thanks,
Marius

—
Marius Messerli, Ph.D.
Lead Activist
Mindliner AG

**Comment by mikrohash** [comment]
Here is an example including a working pom.xml on how to use the latest iota.lib.java snapshot with Maven by locally installing the library: https://github.com/mikrohash/jota-example

**Comment by marimes** [comment]
Many thanks for getting back - appreciate. Just tried it and got the following error after `mvn install`:
```[ERROR] Failed to execute goal on project jota-example: Could not resolve dependencies for project com.github.mikrohash:jota-example:jar:1.0: Could not find artifact com.github.iotaledger:iota.lib.java:jar:0.9.11-SNAPSHOT -> [Help 1]```

**Comment by mikrohash** [comment]
Looks like something went wrong when you tried to locally install the iota.lib.java. Did you get any errors when you ran this command in step 2 of the guide:

    mvn install:install-file -Dfile=jota/target/jota-0.9.11-SNAPSHOT.jar -DgroupId=com.github.iotaledger -DartifactId=iota.lib.java -Dversion=0.9.11-SNAPSHOT -Dpackaging=jar

**Comment by d35h** [comment]
Hi Marimes,

if you were following my previous advice then you can put the following into your pom.xml and it should work:
<dependency>
            <groupId>org.iota</groupId>
            <artifactId>jota</artifactId>
            <version>0.9.11-SNAPSHOT</version>
        </dependency>

**Comment by mikrohash** [comment]
That does indeed work. How did I not found out earlier. Thank you @d35h

**Comment by d35h** [comment]
No worries :)

**Comment by marimes** [comment]
Thank you both for your input. Now I have a working setup 👍

**Comment by Fabryprog** [comment]
Hello everyone, can you push jar into maven central repo? 

Without this issue we cannot merge apache camel-iota component https://github.com/apache/camel/pull/2522

**Comment by Fabryprog** [comment]
@kwek20 i just am able to compile this library. To solve my PR into apache camel project is mandatory to push jar into maven central repository. Can you do it for me? 

Read it: https://maven.apache.org/repository/guide-central-repository-upload.html

**Comment by kwek20** [comment]
Hey @Fabryprog

I've had a chat about it and we have decided to not yet release on maven, since were still on a pre-release.
We are working on getting everything set up though (I need some accounts transferred etc)
Is there a particular reason you wont use Jitpack?

**Comment by pinpong** [comment]
@kwek20 I got an notification you want to join bintray iotaledger organization.
Are you a official iota team member?

**Comment by Fabryprog** [comment]
@kwek20 are you sure you do not want to make the library accessible on maven central? Apache camel is a big opensource project with thousand of specialist. it's a shame not to take advantage of this opportunity. make the library usable by maven central you only have to benefit fpr all iota community

**Comment by Fabryprog** [comment]
@kwek20 sorry man but we decided that remove this library. We will use http request directly

King regards

**Comment by kwek20** [comment]
@Fabryprog No problem! Want me to give you a ping when were on maven?

**Comment by Fabryprog** [comment]
@kwek20 yes man. Ping me :-)

**Comment by pinpong** [comment]
@kwek20 maybe a permission issue please check Travis and no, i'm still active. Your are added as member.

**Comment by kwek20** [comment]
Cool, i'll close this ticket and tag you in a new one
