### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by d35h** [iotaledger/iota.lib.java#89]
Hi,

I know that there was a closed issue on this matter: #72.

However, I am still experiencing this problem when trying to use the latest version (v0.9.10) of iota, it works with v0.9.6 though.

I am using this approach:
To use the IOTA Java library in your Maven build add this to your root pom.xml file:
```
 <repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```
Add this in your module pom.xml file:
```
<dependency>
    <groupId>com.github.iotaledger</groupId>
    <artifactId>iota~lib~java</artifactId>
    <version>0.9.10</version>
</dependency>
```

I am facing the following problem:
```
Could not resolve dependencies for project com.mycompany.app:my-app:jar:1.0-SNAPSHOT: Failed to collect dependencies at com.github.iotaledger:iota.lib.java:jar:v0.9.10 -> com.github.iotaledger.iota.lib.java:jota:jar:v0.9.10: Failed to read artifact descriptor for com.github.iotaledger.iota.lib.java:jota:jar:v0.9.10: Could not transfer artifact com.github.iotaledger.iota.lib.java:jota:pom:v0.9.10 from/to jitpack.io (https://jitpack.io): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]
```

Any idea?

Thanks,
Dan

**Comment by marimes** [comment]
Seems like a similar problem here: `[ERROR] 'dependencies.dependency.groupId' for com.github.iotaledger.iota~lib~java:jota:jar with value 'com.github.iotaledger.iota~lib~java' does not match a valid id pattern. @ line 27, column 22` (using Maven 3.5.2, Java  1.8.0_152, mac os x version: 10.13.3).

**Comment by ModSeven** [comment]
Same problem here, is there a fix in work?

**Comment by mikrohash** [comment]
Here is an example including a working pom.xml on how to use the latest iota.lib.java snapshot with Maven by locally installing the library: https://github.com/mikrohash/jota-example

**Comment by d35h** [comment]
@ModSeven see comments at #72

**Comment by matthiaszimmermann** [comment]
same here, working against a local clone (0.9.11-snapshot). this works but feels "hacky". please provide some reliable mechanism to work with tags. tx

**Comment by mbe24** [comment]
Why even include special characters in an artifact name? Just change the name in a future version...

**Comment by mbe24** [comment]
Following dependency works (Cf. https://jitpack.io/#iotaledger/iota.lib.java)

```
<dependency>
	    <groupId>com.github.iotaledger.iota.lib.java</groupId>
	    <artifactId>jota</artifactId>
	    <version>0.9.10</version>
</dependency>
```

**Comment by kwek20** [comment]
Hey all!

I have updated the maven instructions in the README. 
Our default jar is exported with just our classes, and no dependencies.
If you wish to get the dependencies jar instead, add the following to your `<dependency>`
`<classifier>jar-with-dependencies</classifier>`

Example:
```
<dependency>
    <groupId>com.github.iotaledger.iota~lib~java</groupId>
    <artifactId>jota</artifactId>
    <classifier>jar-with-dependencies</classifier>
    <version>17e0de8ed5</version>
</dependency>
```

You can replace the version with any other hash (first 10 characters), or a release tag. 
Classifier does not work for 0.9.9 and 0.9.10 because those entire builds are broken.. A new one is on its way! (probably including a name change!) 

Please let me know if you have any questions!
