### ISSUE TITLE
Can't get library installed

### ISSUE THREAD

**Issue by usertobi** [iotaledger/iota.lib.java#97]
I am getting the error "Missing artifact".  Marven-wrapper jar is in place. However, where is the "build file"?

I am using Eclipse and a Maven project

**Comment by kwek20** [comment]
@usertobi 

Hey I have updated the README, please refer to the manual install instead of the maven section(jitpack is currently broken)

Thank you,
Brord

**Comment by kwek20** [comment]
Hey @usertobi, Jitpack is fixed

I have updated the maven instructions in the README, again :). 
Our default jar is exported with just our classes, and no dependencies.
If you wish to get the dependencies jar instead, add the following to your `<dependency>`
`<classifier>jar-with-dependencies</classifier>`

Example:
```
<dependency>
    <groupId>com.github.iotaledger.iota~lib~java</groupId>
    <artifactId>jota</artifactId>
    <classifier>jar-with-dependencies</classifier>
    <version>17e0de8ed5</version>
</dependency>
```

You can replace the version with any other hash (first 10 characters), or a release tag. 

Please let me know if you have any questions!
